version: '3.8'
volumes:
  pgdata:
  static:
  media:
  web-root:
services:
  python: &python
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - web-root:/var/www/html
    environment:
      - TOKEN=***
    ports:
      - 8000:8000
    command: uvicorn asgi:start_webhook --log-level=info --workers 1

  redis:
    image: library/redis:6.0.9-alpine
    restart: always
    volumes:
      - ./docker/redis/etc/redis.conf:/data/redis/redis.conf
      - ./docker/redis/data/bases:/data/bases
      - ./docker/redis/data/log:/data/log
    ports:
      - 6379:6379
    command: redis-server /data/redis/redis.conf

  celery_worker:
    <<: *python
    command: celery -A tbot worker --loglevel=info -E -B
    ports: []
    restart: always
    depends_on:
      - redis
